substitutions:
  name: tracer
  prefix: MPPT
  update_interval: 15s
  disabled_by_default: 'true'
  DI: GPIO19
  RO: GPIO18
  REDE: GPIO23
  timezone: Europe/Berlin
esphome:
  name: tracer
  project:
    name: cubinet-code.epever_mppt_controller
    version: 1.0.0
  build_path: .esphome/build/tracer
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
  min_version: 2022.12.3
esp32:
  board: esp-wrover-kit
  framework:
    version: 2.0.5
    source: ~3.20005.0
    platform_version: platformio/espressif32 @ 5.2.0
    type: arduino
  variant: ESP32
text_sensor:
- platform: modbus_controller
  modbus_controller_id: epever
  name: 'MPPT SPEC: Product ID'
  custom_command:
  - 0x01
  - 0x2B
  - 0x0E
  - 0x01
  - 0x00
  - 0x70
  - 0x77
  response_size: 103
  raw_encode: COMMA
  lambda: !lambda |-
    ESP_LOGE("epever", "Device ID %s", x);
    return x;
  disabled_by_default: false
  bitmask: 0xFFFFFFFF
  skip_updates: 0
  force_new_range: false
  register_count: 0
wifi:
  domain: .local
  reboot_timeout: 15min
  power_save_mode: LIGHT
  fast_connect: false
  networks:
  - ssid: EXTREME
    password: X2erZisRGFM7MepT
    priority: 0.0
  use_address: tracer.local
dashboard_import:
  package_import_url: github://cubinet-code/esphome-packages/epever_mppt_controller.yaml@main
  import_full_config: false
web_server:
  port: 80
  version: 2
  include_internal: false
  ota: true
  css_url: ''
  js_url: https://oi.esphome.io/v2/www.js
time:
- platform: homeassistant
  id: hass_time
  update_interval: 24h
  on_time_sync:
  - then:
    - script.execute:
        id: update_rtc
  timezone: CET-1CEST,M3.5.0,M10.5.0/3
- platform: sntp
  id: sntp_time
  update_interval: 24h
  timezone: CET-1CEST,M3.5.0,M10.5.0/3
  servers:
  - de.pool.ntp.org
  on_time_sync:
  - then:
    - script.execute:
        id: update_rtc
logger:
  level: VERBOSE
  baud_rate: 115200
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  logs: {}
api:
  reboot_timeout: 0s
  port: 6053
  password: ''
ota:
  on_error:
  - then:
    - button.press:
        id: restart_button
  safe_mode: true
  port: 3232
  reboot_timeout: 5min
  num_attempts: 10
uart:
- tx_pin:
    number: 19
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    drive_strength: 20.0
  rx_pin:
    number: 18
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    drive_strength: 20.0
  baud_rate: 115200
  stop_bits: 1
  rx_buffer_size: 256
  data_bits: 8
  parity: NONE
modbus:
- flow_control_pin:
    number: 23
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    drive_strength: 20.0
  send_wait_time: 200ms
modbus_controller:
- id: epever
  address: 0x01
  update_interval: 15s
  command_throttle: 0ms
sensor:
- platform: wifi_signal
  name: MPPT ESP WiFi Signal
  update_interval: 15s
  entity_category: diagnostic
  disabled_by_default: false
  force_update: false
  unit_of_measurement: dBm
  accuracy_decimals: 0
  device_class: signal_strength
  state_class: measurement
button:
- platform: restart
  id: restart_button
  name: MPPT ESP Restart
  entity_category: diagnostic
  disabled_by_default: false
  device_class: restart
script:
- id: update_rtc
  then:
  - lambda: !lambda |-
      auto now = id(sntp_time).now();

      if (!now.is_valid()) {
        ESP_LOGW("epever_mppt_controller", "RTC not valid yet. Skipping RTC Update.");
        return;
      }

      int s = now.second;
      int m = now.minute;
      int h = now.hour;
      int d = now.day_of_month;
      int M = now.month;
      int y = now.year % 100;

      uint16_t r1 = ((m << 8) | s);
      uint16_t r2 = ((d << 8) | h);
      uint16_t r3 = ((y << 8) | M);

      std::vector<uint16_t> rtc_data = {
        r1, r2, r3
      };

      for(std::vector<uint16_t>::size_type i = 0; i != rtc_data.size(); i++) {
        ESP_LOGI("epever_mppt_controller", "RTC Data to be sent: 0x%x: 0x%x", i + 0x9013, rtc_data[i]);
      }

      esphome::modbus_controller::ModbusController *controller = id(epever);
      esphome::modbus_controller::ModbusCommandItem cmd =
          esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
            controller, 0x9013, 3, rtc_data
          );
      delay(200);
      controller->queue_command(cmd);
      delay(200);

      ESP_LOGI("epever_mppt_controller", "RTC updated to %04d-%02d-%02d %02d:%02d:%02d", y+2000, M, d, h, m, s);
  mode: single
  parameters: {}

